sudo: required
services:
  - docker

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    test -e Gemfile || cat <<EOF > Gemfile
    source 'https://rubygems.org'
    gem 'rake'
    gem 'test-kitchen'
    gem 'kitchen-docker'
    gem 'kitchen-inspec'
    gem 'inspec'
    gem 'kitchen-salt', :git => 'https://github.com/salt-formulas/kitchen-salt.git'
  - bundle install

env:
    - PLATFORM=trevorj/salty-whales:trusty SUITE=compute_dpdk
    - PLATFORM=trevorj/salty-whales:xenial SUITE=compute_dpdk
    - PLATFORM=trevorj/salty-whales:trusty SUITE=compute_dvr
    - PLATFORM=trevorj/salty-whales:xenial SUITE=compute_dvr
    - PLATFORM=trevorj/salty-whales:xenial SUITE=compute_dvr_fwaas_v1
    - PLATFORM=trevorj/salty-whales:trusty SUITE=compute_legacy
    - PLATFORM=trevorj/salty-whales:xenial SUITE=compute_legacy
    - PLATFORM=trevorj/salty-whales:trusty SUITE=compute_nonexternal_dvr
    - PLATFORM=trevorj/salty-whales:xenial SUITE=compute_nonexternal_dvr
    - PLATFORM=trevorj/salty-whales:trusty SUITE=compute_sriov
    - PLATFORM=trevorj/salty-whales:xenial SUITE=compute_sriov
    - PLATFORM=trevorj/salty-whales:trusty SUITE=compute_qos_sriov
    - PLATFORM=trevorj/salty-whales:xenial SUITE=compute_qos_sriov
    - PLATFORM=trevorj/salty-whales:trusty SUITE=compute_qos
    - PLATFORM=trevorj/salty-whales:xenial SUITE=compute_qos
    - PLATFORM=trevorj/salty-whales:trusty SUITE=control_cluster
    - PLATFORM=trevorj/salty-whales:xenial SUITE=control_cluster
    - PLATFORM=trevorj/salty-whales:trusty SUITE=control_dvr
    - PLATFORM=trevorj/salty-whales:xenial SUITE=control_dvr
    - PLATFORM=trevorj/salty-whales:trusty SUITE=control_nodvr
    - PLATFORM=trevorj/salty-whales:xenial SUITE=control_nodvr
    - PLATFORM=trevorj/salty-whales:trusty SUITE=control_single
    - PLATFORM=trevorj/salty-whales:xenial SUITE=control_single
    - PLATFORM=trevorj/salty-whales:xenial SUITE=control_lbaas_octavia
    - PLATFORM=trevorj/salty-whales:xenial SUITE=control_fwaas_v1
    - PLATFORM=trevorj/salty-whales:trusty SUITE=control_qos
    - PLATFORM=trevorj/salty-whales:xenial SUITE=control_qos
    - PLATFORM=trevorj/salty-whales:trusty SUITE=gateway_dvr
    - PLATFORM=trevorj/salty-whales:xenial SUITE=gateway_dvr
    - PLATFORM=trevorj/salty-whales:trusty SUITE=gateway_legacy
    - PLATFORM=trevorj/salty-whales:xenial SUITE=gateway_legacy
    - PLATFORM=trevorj/salty-whales:trusty SUITE=gateway_qos
    - PLATFORM=trevorj/salty-whales:xenial SUITE=gateway_qos
    - PLATFORM=trevorj/salty-whales:xenial SUITE=gateway_legacy_fwaas_v1

before_script:
  - set -o pipefail
  - make test | tail

script:
  - KITCHEN_LOCAL_YAML=.kitchen.travis.yml bundle exec kitchen test -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: never    # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false
